name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build Release
      run: cargo build --release
    - name: Strip the binary
      run: strip target/release/docker-cron
    - name: Archive Release Binary
      run: zip -j docker-cron.zip target/release/docker-cron
    - name: Upload Release Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./docker-cron.zip
        asset_name: docker-cron.zip
        asset_content_type: application/zip

