name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build Release
      run: cargo build --release
    - name: Strip the binary
      run: strip target/release/docker-cron
    - name: Archive Release Binary
      run: zip -j docker-cron.zip target/release/docker-cron README.md
    - name: Upload Release Binary
      uses: softprops/action-gh-release@v2
      with:
        files: docker-cron.zip
        token: ${{ secrets.GITHUB_TOKEN }}
